char *s = N_("<b>Preferences</b>");
char *s = N_("Apply");
char *s = N_("Cancel");
char *s = N_("Editor");
char *s = N_("Grid spacing");
char *s = N_("Port");
char *s = N_("Preferences");
char *s = N_("Server");
char *s = N_("Show grid");
