#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Libraries
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk


from harpia.GUI.mainwindow import MainWindow
from harpia.control.maincontrol import MainControl

import sys, argparse
import os

#---------------------------------------------------
#--------HARPIA FRONTEND MAIN FUNCTION--------------
#---------------------------------------------------

def main(argv):
    """
            The Harpia-Frontend class is where the main function starts the system.
            It initializes the interface.
    """

    #export data folder's path

    #if os.getcwd() == '/home/nofx/pkgHarpia/harpia':
        #os.environ['HARPIA_DATA_DIR'] = "app_data/"
    #else:
    os.environ['HARPIA_DATA_DIR']="/usr/share/harpia/"


	## Initialize the Frontend
    win = MainWindow()
    win.show_all()

	## Parameter passing
    parser = argparse.ArgumentParser()
    parser.add_argument("-o", "--open", help="Open file")
    args = parser.parse_args()
    if len(sys.argv) == 1:
        win.main_control.new()
    if args.open:
        win.main_control.open(args.open)

    Gtk.main()
    #----------------------------------------------------------------------

if __name__ == '__main__':
    main(sys.argv)

    #----------------------------------------------------------------------
