#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Libraries
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk


from harpia import s2idirectory
from harpia.model.diagrammodel import DiagramModel
from harpia.model.connectionmodel import ConnectionModel
from harpia.control.diagramcontrol import DiagramControl
from harpia.control.codegenerator import CodeGenerator


import sys
import argparse
import os

#---------------------------------------------------
#--------HARPIA FRONTEND MAIN FUNCTION--------------
#---------------------------------------------------

class Log(object):
    def log(self, msg):
        print msg

def main(argv):

    os.environ['HARPIA_DATA_DIR']="/usr/share/harpia/"
    s2idirectory.load()
    s2idirectory.Log = Log()

    parser = argparse.ArgumentParser()
    parser.add_argument("-x", "--examples", help="Generate examples", action='store_false')
    parser.add_argument("-c", "--compile", help="Compile examples", action='store_false')
    args = parser.parse_args()

    for key in s2idirectory.block:
        obj = s2idirectory.block[key]()
        obj.x = 200
        diagram = DiagramModel()
        diagram.add_block(obj)
 
        cont = 0
        intypes = obj.get_description()["InTypes"]
        for inkey in intypes:
            if intypes[inkey] == "HRP_IMAGE":
                block = s2idirectory.block["harpia.plugins.imageFile"]()
            elif intypes[inkey] == "HRP_INT":
                block = s2idirectory.block["harpia.plugins.intValue"]()
            elif intypes[inkey] == "HRP_DOUBLE":
                block = s2idirectory.block["harpia.plugins.newDouble"]()
            elif intypes[inkey] == "HRP_RECT":
                block = s2idirectory.block["harpia.plugins.newRect"]()
            elif intypes[inkey] == "HRP_POINT":
                block = s2idirectory.block["harpia.plugins.newPoint"]()
            diagram.add_block(block)
            block.y = 100 * cont
            diagram.connect_blocks(block, 0, obj, cont)

            cont = cont + 1

        cont = 0
        outtypes = obj.get_description()["OutTypes"]
        for outkey in outtypes:
            if outtypes[outkey] == "HRP_IMAGE":
                show = s2idirectory.block["harpia.plugins.show"]()
                show.x = 400
                diagram.add_block(show)
                diagram.connect_blocks(obj, cont, show, 0)
            cont = cont + 1

        if args.examples:
            # Save Examples
            diagram.set_file_name("/tmp/" + obj.get_description()["Label"] + ".hrp")
            print "Generating", diagram.get_file_name(), "file"
            control = DiagramControl(diagram)
            control.save()

        if args.compile:
            # Compile Examples
            print "Generating code..."
            generator = CodeGenerator(diagram)
            generator.compile()
            print obj.get_description()["Label"], " - compiled\n"

    #----------------------------------------------------------------------

if __name__ == '__main__':
    main(sys.argv)

    #----------------------------------------------------------------------
