#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Libraries
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk


from harpia.GUI.mainwindow import MainWindow
from harpia.control.maincontrol import MainControl

import sys
import argparse
import os

#---------------------------------------------------
#--------HARPIA FRONTEND MAIN FUNCTION--------------
#---------------------------------------------------


def main(argv):
    """
            The Harpia-Frontend class is where the main function starts the system.
            It initializes the interface.
    """

    reload(sys)
    sys.setdefaultencoding('utf8')

    os.environ['HARPIA_DATA_DIR'] = "/usr/share/harpia/"

    # Initialize the Frontend
    win = MainWindow()
    win.show_all()

    # Parameter passing
    parser = argparse.ArgumentParser()
    parser.add_argument('file', default=[], nargs='*',
                        help="List of files to open")
    args = parser.parse_args()

    if args.file:
        for arg in args.file:
            win.main_control.open(arg)
    else:
        win.main_control.new()

    # to kill with Terminal Ctrl+C
    import signal
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    Gtk.main()
    #----------------------------------------------------------------------

if __name__ == '__main__':
    main(sys.argv)

    #----------------------------------------------------------------------
