.\" Manpage for Harpia.
.\" Contact ___@ufsj.edu.br to correct errors or typos.
.TH man 1 "21 October 2016" "1.0a7" "Harpia man page"
.SH NAME
harpia - run harpia, harpia name_example - load or create the code.
.SH SYNOPSIS
harpia
.SH DESCRIPTION
harpia is a tool for computer vision, image processing and code generating.
.SH OPTIONS
harpia [path/program_name] - create or load the code.
.SH EXAMPLES
harpia /usr/share/harpia/examples/And.hrp -- Load example And.hrp
.SH SEE ALSO
Coming soon.
.SH BUGS
No known bugs.
.SH AUTHOR
Ouroboros (___@ufsj.edu.br)
