.\" Manpage for Mosaicode.
.\" Contact ___@ufsj.edu.br to correct errors or typos.
.TH man 1 "21 October 2016" "1.0a7" "Mosaicode man page"
.SH NAME
mosaicode - run mosaicode, mosaicode name_example - load or create the code.
.SH SYNOPSIS
mosaicode
.SH DESCRIPTION
mosaicode is a tool for computer vision, image processing and code generating.
.SH OPTIONS
mosaicode [path/program_name] - create or load the code.
.SH EXAMPLES
mosaicode /usr/share/mosaicode/examples/And.mscd -- Load example And.mscd
.SH SEE ALSO
Coming soon.
.SH BUGS
No known bugs.
.SH AUTHOR
Ouroboros (___@ufsj.edu.br)
